# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
stringData:
  config.env: ENC[AES256_GCM,data:kRSXfakiPZj/SljklCFA24jHVhog6Bg3Ev+Z+oANG+9xCSiveqbd7mx4T9TrsTIqt3BFI05x1hZnKoS0irxUIPZ5T/+aExyH0sfEfbd4sxQ+,iv:UK24AGJM3DGKLUJumrd60FpMcwcD0rk0apQ6XV7jPTg=,tag:xDjm734ZrMjgIGO5Gwo4wA==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvLzExZzE1WUxxMHU5T1hG
        M1FJM3RHb1ZLWkpZUVhVdmJ3U0J6bjRkM0RVCi93UWFoTStnbGxhMHY5ZWx0WDhJ
        WlgxRTBtS21ubXhQTWphTXQvRUVVOEEKLS0tIHI3N0ZnVzVYZ1Q4UFBHb3FtTU9q
        YTQyQllIdCtscHpuQXpFakJuZStDWlUKTUTAeCgkxh2sNAcV0j+6oOdiBLPVfTYA
        WdI/uIZBnJpDfDHHW2AE1G8tuddOLBf2eS6f4mbHeCRMghpPGF7hxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T07:09:10Z"
  mac: ENC[AES256_GCM,data:MeEkrwaL+Hbu9CVTYJZttUn+PmBbC8c/Q5KzqPS0B2OXvGQeU68vbcjbGrXxGsUjkzvj4+6E3BCPwqFutmDg9MqiODuZaWUhvZ8KpSiWoBPv1i+zXfZALYNIuZnjF1UFk+o/nSvB/rAheNsAhRtvLlMHhF472dS3BhM+VF2grfE=,iv:hglRO/vpcJWeYAVIZ/C9JvVvA29iBVqiwqPCsL9gtOI=,tag:Da1r93ByttbprqXMQ0HDaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
