# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-keycloak
stringData:
  AUTH_KEYCLOAK_SECRET: ENC[AES256_GCM,data:vMKMGKNe6ouvc25Zog==,iv:7hgJWyvHUNO4A9W60BxjV+mlJX++n2VLSlQzQXlLqvc=,tag:e/5EV8VWyWNRJpN1Uo+XOQ==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRTVrY3VpSUpvNEFLd0M5
        c05YM3drd001WlVCNDlhazVkYWxPNzlLMW1NCndLbFJjdFRqbWMyRGg1MUwvZHQ2
        UTdZc0kzTGoxM3RkK3E5K1VUbWdzYkUKLS0tIFd1NnZ6V3JIbEcrWmVGZjluQnln
        Yit4bFdwVE5WbXpBaVNPbTM4eVhZS3cKNUJCDb2jSou0754J8Ge0QWV8GoqTFhrT
        HuBien2aluZm2v5EhEm1w9avRXcWdwOGVzvVftAdHzBguFYmPf5CCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T05:54:56Z"
  mac: ENC[AES256_GCM,data:Ish6HZY5vzEJMLbrKwsxPsWuYiS/Q/qz2uMg8eOKaqVAB40Yxl2FHSPCbf63SikRbf/vx5Qf1DtG0zXXyYoSTiinqgYIuI0Dox+OoZme//E4EcMaENXO/hnkTa4D5E3VE4CbDM9vyoGAS2f+a66lSDmIYMa3WDelApFAR0yVabU=,iv:WA3j4+UuoCDNjPJGnNz+aOAdO+w2fquxrPJAs82vepw=,tag:wKhSQKC1Ji02/I/QS4cOJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
