# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-keycloak
stringData:
  KC_CLIENT_SECRET: ENC[AES256_GCM,data:LwpjQtsGx/KaTd2E5w==,iv:gLNeo5cOZqFtVFQ9HA3o1MsAimOc2OI0iavuFbUXejs=,tag:4owZlI9GuoDv7h2qbdYRow==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkMwZDgyWDNMVVdXTzRF
        ajI0UEU4c211QmF1M05WYnMxM2dzd0lwM0hJCmp2UHByK1BWQmxHRmZ6TERKaG1I
        d0RqSzllOG9IWVV4bmJjaVJVZ1Jla2MKLS0tIHpueHVueDYySzZQTG1MbmZ6Qlhx
        ZDk2Q1dqMjBkRHBVZUJKOHRqTGZlRFEKgO02yVH51nMxzBVDgzl3L06/9PSH4mtl
        G2pWYoJYvGwybST9MtaWqGSKLhG+uUWxQuvw65Fs5rsRV6XKSmWEKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-04T05:55:18Z"
  mac: ENC[AES256_GCM,data:hI9YOjYhrSc6jG265omjYQhx2sPjKVY7RHGC2FdiI2fDYoA5gfrfVzosDHP2ibdLh5RFj7WdHLsmUN6icg3+OFAGCgw7SxPLfpHeV1RBmCFPiIv0mryFxmtnksT1HWNGrNiwmbtxt94Prlb15kkFeQOCj8PNFxyCW2REGanERGM=,iv:54qhDtkG+fj2DRIhV6JUzDersl0ckkXssi3+NmXSvt4=,tag:CRB+u9ONMOw89yQy3qspBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
