# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-keycloak
stringData:
  KC_CLIENT_SECRET: ENC[AES256_GCM,data:0sAs,iv:34i9aS2k5w3me5Z82IkVaAl29w1/lKJNbWxNFnoOaiA=,tag:bGEG9VcJH5/MunKWkS0Paw==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbkx6eC9xT29DYkxtTkY4
        dmI5K3hJN0MwVDVBckJpNWQrbCtFU21tQ2xVCjMvWW9POTFVVFpXUk5xMjdQVjFN
        QTBvYnFtU1I5QUNKT3dSUDdrMjZWdncKLS0tIEFzSVpUMXViUVlZWmFXUUpOc3BK
        VjNBZ0liVUV3U0djVWI4U2F0KythYUkKlusyOH7dJihV7muZK7ea0F5tYpQYFX3w
        6K8d+lQAKiUC5Yp4Pu78xVLz0GvTFrIxdBVyr16+ImjMrqkkeO3ilg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T16:00:37Z"
  mac: ENC[AES256_GCM,data:EUbv5p9jL+Q/7+294QctSFeFh3fEITeWIpNNQfNzGVw+ZMYfdoAmdnmkUzgMs98PVUc52PIzXh9lmgcjdrFpDHu/f3hbpPlqWwMOumwO64DIy/vjFP/tM5Uy3UsjJYNz31pkJgxkyFprEdDEf0l4KG9Vo6+GAsAEZSvhaM/A1WE=,iv:tQoGSLMkxTsq71qmM7pweZxj3OBV1ororNrwXIRkjI4=,tag:ruCujOa1q25juI8F7Dm5LQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
